//This file will declare some functions to collect data during a trial, and send that data to the gui.


struct Trial_Data
{
  //# of steps for a given trial
  unsigned int steps = 0;
  //millis() reference for each step, used to determine if step should count
  unsigned long int step_start;
  //Delay to warrant incrementing the step counter
  const int kstep_delay = 250;
  //Trial start time
  unsigned long int trial_start;
  //Int where total steps is stored in EEPROM (See memory map in drive)
  const int kaddr = 183;

  //Flags used by message functions to send steps and time
  const char step_flag = 'l';

  //Nominal Ankle moment at every other percent of gait phase (including zero)
  const float nominal_moment_array [51] = {
    //Must be generated by trial and Italics(error), possibly averaged with several people in the lab. (Yes that's how you explicitly type cast to italics).
  };
};

//Step counter instance
Trial_Data trial_value = Trial_Data();
//Pointer to step counter instance
Trial_Data* stepper = &trial_value;
